### ISSUE TITLE
Incorrect documentation preview when template contains a $ref

### ISSUE THREAD

**Issue by rovellipaolo** [failsafe-engineering/serverless-aws-apigateway-documentation#45]
When generating a documentation preview locally, with `serverless generateDocumentation` command, the documentation will not be generated correctly if the template contains a reference to another local model with the `$ref` keyword.

For example the following template (taken directly from the `README.md` file):
```
custom:
  documentation:
    models:
      -
        name: "Customer"
        description: "This is a customer"
        contentType: "application/json"
        schema:
          type: "object"
          properties:
            name:
              type: "string"
            address:
              $ref: "{{model: Address}}"
```
will generate the following documentation preview:
```
"components": {
  "schemas": {
    "Customer": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "address": {
          "$ref": "{{model: Address}}"
        }
      }
    }
  }
}
```
As you can see the `$ref` value is `"{{model: Address}}"` (wrong) rather than `"#/components/schemas/Address"` (correct).

**NOTE:** The documentation preview will be generated correctly if the reference is to a URL (e.g., `"http://path/to/your/resource"`).

Although it's expected that the documentation preview might _potentially_ be invalid or anyway different from the final documentation (which is why it's called _"preview"_), it would be nice to fix this use-case.
